/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.ceffective.scoping;

import org.xtext.example.ceffective.scoping.AbstractCeffectiveScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class CeffectiveScopeProvider extends AbstractCeffectiveScopeProvider {
}
