/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.ceffective;

import org.xtext.example.ceffective.CeffectiveStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class CeffectiveStandaloneSetup extends CeffectiveStandaloneSetupGenerated {
  public static void doSetup() {
    CeffectiveStandaloneSetup _ceffectiveStandaloneSetup = new CeffectiveStandaloneSetup();
    _ceffectiveStandaloneSetup.createInjectorAndDoEMFRegistration();
  }
}
