/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.ceffective;

import org.xtext.example.ceffective.AbstractCeffectiveRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class CeffectiveRuntimeModule extends AbstractCeffectiveRuntimeModule {
}
