/*
 * generated by Xtext 2.10.0
 */
package org.xtext.example.ceffective.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractCeffectiveScopeProvider extends DelegatingScopeProvider {
}
