/*
 * generated by Xtext 2.10.0
 */
package org.xtext.example.ceffective.ide.contentassist.antlr;

import com.google.inject.Inject;
import java.util.Collection;
import java.util.HashMap;
import java.util.Map;
import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ide.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;
import org.xtext.example.ceffective.ide.contentassist.antlr.internal.InternalCeffectiveParser;
import org.xtext.example.ceffective.services.CeffectiveGrammarAccess;

public class CeffectiveParser extends AbstractContentAssistParser {

	@Inject
	private CeffectiveGrammarAccess grammarAccess;

	private Map<AbstractElement, String> nameMappings;

	@Override
	protected InternalCeffectiveParser createParser() {
		InternalCeffectiveParser result = new InternalCeffectiveParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getAutenticacionUsuarioAccess().getAlternatives(), "rule__AutenticacionUsuario__Alternatives");
					put(grammarAccess.getMecanismoSeguridadAccess().getAlternatives(), "rule__MecanismoSeguridad__Alternatives");
					put(grammarAccess.getRecursoAccess().getAlternatives(), "rule__Recurso__Alternatives");
					put(grammarAccess.getEStringAccess().getAlternatives(), "rule__EString__Alternatives");
					put(grammarAccess.getTipoAmbienteAccess().getAlternatives(), "rule__TipoAmbiente__Alternatives");
					put(grammarAccess.getTamanoServidorAccess().getAlternatives(), "rule__TamanoServidor__Alternatives");
					put(grammarAccess.getTipoBaseDatosAccess().getAlternatives(), "rule__TipoBaseDatos__Alternatives");
					put(grammarAccess.getCeffectiveAccess().getGroup(), "rule__Ceffective__Group__0");
					put(grammarAccess.getCeffectiveAccess().getGroup_3(), "rule__Ceffective__Group_3__0");
					put(grammarAccess.getProveedorNubeAccess().getGroup(), "rule__ProveedorNube__Group__0");
					put(grammarAccess.getProveedorNubeAccess().getGroup_2(), "rule__ProveedorNube__Group_2__0");
					put(grammarAccess.getProveedorNubeAccess().getGroup_3(), "rule__ProveedorNube__Group_3__0");
					put(grammarAccess.getProveedorNubeAccess().getGroup_7(), "rule__ProveedorNube__Group_7__0");
					put(grammarAccess.getProveedorNubeAccess().getGroup_9(), "rule__ProveedorNube__Group_9__0");
					put(grammarAccess.getProveedorNubeAccess().getGroup_9_3(), "rule__ProveedorNube__Group_9_3__0");
					put(grammarAccess.getProveedorNubeAccess().getGroup_10(), "rule__ProveedorNube__Group_10__0");
					put(grammarAccess.getProveedorNubeAccess().getGroup_10_3(), "rule__ProveedorNube__Group_10_3__0");
					put(grammarAccess.getAutenticacionUsuario_ImplAccess().getGroup(), "rule__AutenticacionUsuario_Impl__Group__0");
					put(grammarAccess.getAutenticacionUsuario_ImplAccess().getGroup_3(), "rule__AutenticacionUsuario_Impl__Group_3__0");
					put(grammarAccess.getAutenticacionUsuario_ImplAccess().getGroup_4(), "rule__AutenticacionUsuario_Impl__Group_4__0");
					put(grammarAccess.getAmbienteDespliegueAccess().getGroup(), "rule__AmbienteDespliegue__Group__0");
					put(grammarAccess.getAmbienteDespliegueAccess().getGroup_3(), "rule__AmbienteDespliegue__Group_3__0");
					put(grammarAccess.getAmbienteDespliegueAccess().getGroup_4(), "rule__AmbienteDespliegue__Group_4__0");
					put(grammarAccess.getAmbienteDespliegueAccess().getGroup_4_3(), "rule__AmbienteDespliegue__Group_4_3__0");
					put(grammarAccess.getVPCAccess().getGroup(), "rule__VPC__Group__0");
					put(grammarAccess.getVPCAccess().getGroup_3(), "rule__VPC__Group_3__0");
					put(grammarAccess.getVPCAccess().getGroup_4(), "rule__VPC__Group_4__0");
					put(grammarAccess.getVPCAccess().getGroup_4_3(), "rule__VPC__Group_4_3__0");
					put(grammarAccess.getAutenticacionBasicaAccess().getGroup(), "rule__AutenticacionBasica__Group__0");
					put(grammarAccess.getAutenticacionBasicaAccess().getGroup_3(), "rule__AutenticacionBasica__Group_3__0");
					put(grammarAccess.getAutenticacionBasicaAccess().getGroup_4(), "rule__AutenticacionBasica__Group_4__0");
					put(grammarAccess.getAutenticacionBasicaAccess().getGroup_5(), "rule__AutenticacionBasica__Group_5__0");
					put(grammarAccess.getAutenticacionFirmaAccess().getGroup(), "rule__AutenticacionFirma__Group__0");
					put(grammarAccess.getAutenticacionFirmaAccess().getGroup_3(), "rule__AutenticacionFirma__Group_3__0");
					put(grammarAccess.getAutenticacionFirmaAccess().getGroup_4(), "rule__AutenticacionFirma__Group_4__0");
					put(grammarAccess.getAutenticacionFirmaAccess().getGroup_5(), "rule__AutenticacionFirma__Group_5__0");
					put(grammarAccess.getAutenticacionFirmaAccess().getGroup_6(), "rule__AutenticacionFirma__Group_6__0");
					put(grammarAccess.getServidorAplicacionesAccess().getGroup(), "rule__ServidorAplicaciones__Group__0");
					put(grammarAccess.getServidorAplicacionesAccess().getGroup_3(), "rule__ServidorAplicaciones__Group_3__0");
					put(grammarAccess.getServidorAplicacionesAccess().getGroup_4(), "rule__ServidorAplicaciones__Group_4__0");
					put(grammarAccess.getServidorAplicacionesAccess().getGroup_5(), "rule__ServidorAplicaciones__Group_5__0");
					put(grammarAccess.getServidorAplicacionesAccess().getGroup_6(), "rule__ServidorAplicaciones__Group_6__0");
					put(grammarAccess.getServidorAplicacionesAccess().getGroup_7(), "rule__ServidorAplicaciones__Group_7__0");
					put(grammarAccess.getServidorAplicacionesAccess().getGroup_8(), "rule__ServidorAplicaciones__Group_8__0");
					put(grammarAccess.getServidorAplicacionesAccess().getGroup_8_3(), "rule__ServidorAplicaciones__Group_8_3__0");
					put(grammarAccess.getServidorAplicacionesAccess().getGroup_9(), "rule__ServidorAplicaciones__Group_9__0");
					put(grammarAccess.getAlmacenamientoAccess().getGroup(), "rule__Almacenamiento__Group__0");
					put(grammarAccess.getAlmacenamientoAccess().getGroup_3(), "rule__Almacenamiento__Group_3__0");
					put(grammarAccess.getAlmacenamientoAccess().getGroup_4(), "rule__Almacenamiento__Group_4__0");
					put(grammarAccess.getAlmacenamientoAccess().getGroup_5(), "rule__Almacenamiento__Group_5__0");
					put(grammarAccess.getAlmacenamientoAccess().getGroup_6(), "rule__Almacenamiento__Group_6__0");
					put(grammarAccess.getAlmacenamientoAccess().getGroup_7(), "rule__Almacenamiento__Group_7__0");
					put(grammarAccess.getAlmacenamientoAccess().getGroup_7_3(), "rule__Almacenamiento__Group_7_3__0");
					put(grammarAccess.getAlmacenamientoAccess().getGroup_8(), "rule__Almacenamiento__Group_8__0");
					put(grammarAccess.getServidorBDAccess().getGroup(), "rule__ServidorBD__Group__0");
					put(grammarAccess.getServidorBDAccess().getGroup_3(), "rule__ServidorBD__Group_3__0");
					put(grammarAccess.getServidorBDAccess().getGroup_4(), "rule__ServidorBD__Group_4__0");
					put(grammarAccess.getServidorBDAccess().getGroup_5(), "rule__ServidorBD__Group_5__0");
					put(grammarAccess.getServidorBDAccess().getGroup_6(), "rule__ServidorBD__Group_6__0");
					put(grammarAccess.getServidorBDAccess().getGroup_7(), "rule__ServidorBD__Group_7__0");
					put(grammarAccess.getServidorBDAccess().getGroup_8(), "rule__ServidorBD__Group_8__0");
					put(grammarAccess.getServidorBDAccess().getGroup_9(), "rule__ServidorBD__Group_9__0");
					put(grammarAccess.getServidorBDAccess().getGroup_9_3(), "rule__ServidorBD__Group_9_3__0");
					put(grammarAccess.getServidorBDAccess().getGroup_10(), "rule__ServidorBD__Group_10__0");
					put(grammarAccess.getServidor_ImplAccess().getGroup(), "rule__Servidor_Impl__Group__0");
					put(grammarAccess.getServidor_ImplAccess().getGroup_3(), "rule__Servidor_Impl__Group_3__0");
					put(grammarAccess.getServidor_ImplAccess().getGroup_4(), "rule__Servidor_Impl__Group_4__0");
					put(grammarAccess.getServidor_ImplAccess().getGroup_5(), "rule__Servidor_Impl__Group_5__0");
					put(grammarAccess.getServidor_ImplAccess().getGroup_6(), "rule__Servidor_Impl__Group_6__0");
					put(grammarAccess.getServidor_ImplAccess().getGroup_7(), "rule__Servidor_Impl__Group_7__0");
					put(grammarAccess.getServidor_ImplAccess().getGroup_7_3(), "rule__Servidor_Impl__Group_7_3__0");
					put(grammarAccess.getServidor_ImplAccess().getGroup_8(), "rule__Servidor_Impl__Group_8__0");
					put(grammarAccess.getEIntAccess().getGroup(), "rule__EInt__Group__0");
					put(grammarAccess.getSubredAccess().getGroup(), "rule__Subred__Group__0");
					put(grammarAccess.getSubredAccess().getGroup_3(), "rule__Subred__Group_3__0");
					put(grammarAccess.getSubredAccess().getGroup_4(), "rule__Subred__Group_4__0");
					put(grammarAccess.getSubredAccess().getGroup_5(), "rule__Subred__Group_5__0");
					put(grammarAccess.getSubredAccess().getGroup_6(), "rule__Subred__Group_6__0");
					put(grammarAccess.getSubredAccess().getGroup_7(), "rule__Subred__Group_7__0");
					put(grammarAccess.getInternetGatewayAccess().getGroup(), "rule__InternetGateway__Group__0");
					put(grammarAccess.getInternetGatewayAccess().getGroup_3(), "rule__InternetGateway__Group_3__0");
					put(grammarAccess.getInternetGatewayAccess().getGroup_4(), "rule__InternetGateway__Group_4__0");
					put(grammarAccess.getInternetGatewayAccess().getGroup_5(), "rule__InternetGateway__Group_5__0");
					put(grammarAccess.getInternetGatewayAccess().getGroup_6(), "rule__InternetGateway__Group_6__0");
					put(grammarAccess.getGrupoSeguridadAccess().getGroup(), "rule__GrupoSeguridad__Group__0");
					put(grammarAccess.getGrupoSeguridadAccess().getGroup_2(), "rule__GrupoSeguridad__Group_2__0");
					put(grammarAccess.getGrupoSeguridadAccess().getGroup_3(), "rule__GrupoSeguridad__Group_3__0");
					put(grammarAccess.getGrupoSeguridadAccess().getGroup_4(), "rule__GrupoSeguridad__Group_4__0");
					put(grammarAccess.getGrupoSeguridadAccess().getGroup_5(), "rule__GrupoSeguridad__Group_5__0");
					put(grammarAccess.getGrupoSeguridadAccess().getGroup_6(), "rule__GrupoSeguridad__Group_6__0");
					put(grammarAccess.getGrupoSeguridadAccess().getGroup_10(), "rule__GrupoSeguridad__Group_10__0");
					put(grammarAccess.getGrupoSeguridadAccess().getGroup_15(), "rule__GrupoSeguridad__Group_15__0");
					put(grammarAccess.getReglaAccess().getGroup(), "rule__Regla__Group__0");
					put(grammarAccess.getReglaAccess().getGroup_3(), "rule__Regla__Group_3__0");
					put(grammarAccess.getReglaAccess().getGroup_4(), "rule__Regla__Group_4__0");
					put(grammarAccess.getReglaAccess().getGroup_5(), "rule__Regla__Group_5__0");
					put(grammarAccess.getReglaAccess().getGroup_6(), "rule__Regla__Group_6__0");
					put(grammarAccess.getReglaAccess().getGroup_7(), "rule__Regla__Group_7__0");
					put(grammarAccess.getCeffectiveAccess().getProveedorNubeAssignment_3_1(), "rule__Ceffective__ProveedorNubeAssignment_3_1");
					put(grammarAccess.getProveedorNubeAccess().getNombreAssignment_2_1(), "rule__ProveedorNube__NombreAssignment_2_1");
					put(grammarAccess.getProveedorNubeAccess().getVpcAssignment_3_1(), "rule__ProveedorNube__VpcAssignment_3_1");
					put(grammarAccess.getProveedorNubeAccess().getAutenticacionUsuarioAssignment_6(), "rule__ProveedorNube__AutenticacionUsuarioAssignment_6");
					put(grammarAccess.getProveedorNubeAccess().getAutenticacionUsuarioAssignment_7_1(), "rule__ProveedorNube__AutenticacionUsuarioAssignment_7_1");
					put(grammarAccess.getProveedorNubeAccess().getAmbientedespliegueAssignment_9_2(), "rule__ProveedorNube__AmbientedespliegueAssignment_9_2");
					put(grammarAccess.getProveedorNubeAccess().getAmbientedespliegueAssignment_9_3_1(), "rule__ProveedorNube__AmbientedespliegueAssignment_9_3_1");
					put(grammarAccess.getProveedorNubeAccess().getMecanismoseguridadAssignment_10_2(), "rule__ProveedorNube__MecanismoseguridadAssignment_10_2");
					put(grammarAccess.getProveedorNubeAccess().getMecanismoseguridadAssignment_10_3_1(), "rule__ProveedorNube__MecanismoseguridadAssignment_10_3_1");
					put(grammarAccess.getAutenticacionUsuario_ImplAccess().getUsuarioAssignment_3_1(), "rule__AutenticacionUsuario_Impl__UsuarioAssignment_3_1");
					put(grammarAccess.getAutenticacionUsuario_ImplAccess().getCorreoAssignment_4_1(), "rule__AutenticacionUsuario_Impl__CorreoAssignment_4_1");
					put(grammarAccess.getAmbienteDespliegueAccess().getAmbienteAssignment_3_1(), "rule__AmbienteDespliegue__AmbienteAssignment_3_1");
					put(grammarAccess.getAmbienteDespliegueAccess().getRecursosAssignment_4_2(), "rule__AmbienteDespliegue__RecursosAssignment_4_2");
					put(grammarAccess.getAmbienteDespliegueAccess().getRecursosAssignment_4_3_1(), "rule__AmbienteDespliegue__RecursosAssignment_4_3_1");
					put(grammarAccess.getVPCAccess().getNombreAssignment_3_1(), "rule__VPC__NombreAssignment_3_1");
					put(grammarAccess.getVPCAccess().getRecursoAssignment_4_2(), "rule__VPC__RecursoAssignment_4_2");
					put(grammarAccess.getVPCAccess().getRecursoAssignment_4_3_1(), "rule__VPC__RecursoAssignment_4_3_1");
					put(grammarAccess.getAutenticacionBasicaAccess().getUsuarioAssignment_3_1(), "rule__AutenticacionBasica__UsuarioAssignment_3_1");
					put(grammarAccess.getAutenticacionBasicaAccess().getCorreoAssignment_4_1(), "rule__AutenticacionBasica__CorreoAssignment_4_1");
					put(grammarAccess.getAutenticacionBasicaAccess().getPasswordAssignment_5_1(), "rule__AutenticacionBasica__PasswordAssignment_5_1");
					put(grammarAccess.getAutenticacionFirmaAccess().getUsuarioAssignment_3_1(), "rule__AutenticacionFirma__UsuarioAssignment_3_1");
					put(grammarAccess.getAutenticacionFirmaAccess().getCorreoAssignment_4_1(), "rule__AutenticacionFirma__CorreoAssignment_4_1");
					put(grammarAccess.getAutenticacionFirmaAccess().getNombreAssignment_5_1(), "rule__AutenticacionFirma__NombreAssignment_5_1");
					put(grammarAccess.getAutenticacionFirmaAccess().getCertificadoAssignment_6_1(), "rule__AutenticacionFirma__CertificadoAssignment_6_1");
					put(grammarAccess.getServidorAplicacionesAccess().getNombreAssignment_3_1(), "rule__ServidorAplicaciones__NombreAssignment_3_1");
					put(grammarAccess.getServidorAplicacionesAccess().getZonaDisponibilidadAssignment_4_1(), "rule__ServidorAplicaciones__ZonaDisponibilidadAssignment_4_1");
					put(grammarAccess.getServidorAplicacionesAccess().getZonaNombreAssignment_5_1(), "rule__ServidorAplicaciones__ZonaNombreAssignment_5_1");
					put(grammarAccess.getServidorAplicacionesAccess().getTamanoAssignment_6_1(), "rule__ServidorAplicaciones__TamanoAssignment_6_1");
					put(grammarAccess.getServidorAplicacionesAccess().getSistemaOperativoAssignment_7_1(), "rule__ServidorAplicaciones__SistemaOperativoAssignment_7_1");
					put(grammarAccess.getServidorAplicacionesAccess().getRecursosAssignment_8_2(), "rule__ServidorAplicaciones__RecursosAssignment_8_2");
					put(grammarAccess.getServidorAplicacionesAccess().getRecursosAssignment_8_3_1(), "rule__ServidorAplicaciones__RecursosAssignment_8_3_1");
					put(grammarAccess.getServidorAplicacionesAccess().getVpcAssignment_9_1(), "rule__ServidorAplicaciones__VpcAssignment_9_1");
					put(grammarAccess.getAlmacenamientoAccess().getNombreAssignment_3_1(), "rule__Almacenamiento__NombreAssignment_3_1");
					put(grammarAccess.getAlmacenamientoAccess().getZonaDisponibilidadAssignment_4_1(), "rule__Almacenamiento__ZonaDisponibilidadAssignment_4_1");
					put(grammarAccess.getAlmacenamientoAccess().getZonaNombreAssignment_5_1(), "rule__Almacenamiento__ZonaNombreAssignment_5_1");
					put(grammarAccess.getAlmacenamientoAccess().getTamanoInicialAssignment_6_1(), "rule__Almacenamiento__TamanoInicialAssignment_6_1");
					put(grammarAccess.getAlmacenamientoAccess().getRecursosAssignment_7_2(), "rule__Almacenamiento__RecursosAssignment_7_2");
					put(grammarAccess.getAlmacenamientoAccess().getRecursosAssignment_7_3_1(), "rule__Almacenamiento__RecursosAssignment_7_3_1");
					put(grammarAccess.getAlmacenamientoAccess().getVpcAssignment_8_1(), "rule__Almacenamiento__VpcAssignment_8_1");
					put(grammarAccess.getServidorBDAccess().getNombreAssignment_3_1(), "rule__ServidorBD__NombreAssignment_3_1");
					put(grammarAccess.getServidorBDAccess().getZonaDisponibilidadAssignment_4_1(), "rule__ServidorBD__ZonaDisponibilidadAssignment_4_1");
					put(grammarAccess.getServidorBDAccess().getZonaNombreAssignment_5_1(), "rule__ServidorBD__ZonaNombreAssignment_5_1");
					put(grammarAccess.getServidorBDAccess().getTamanoAssignment_6_1(), "rule__ServidorBD__TamanoAssignment_6_1");
					put(grammarAccess.getServidorBDAccess().getTipoAssignment_7_1(), "rule__ServidorBD__TipoAssignment_7_1");
					put(grammarAccess.getServidorBDAccess().getSistemaManejadorAssignment_8_1(), "rule__ServidorBD__SistemaManejadorAssignment_8_1");
					put(grammarAccess.getServidorBDAccess().getRecursosAssignment_9_2(), "rule__ServidorBD__RecursosAssignment_9_2");
					put(grammarAccess.getServidorBDAccess().getRecursosAssignment_9_3_1(), "rule__ServidorBD__RecursosAssignment_9_3_1");
					put(grammarAccess.getServidorBDAccess().getVpcAssignment_10_1(), "rule__ServidorBD__VpcAssignment_10_1");
					put(grammarAccess.getServidor_ImplAccess().getNombreAssignment_3_1(), "rule__Servidor_Impl__NombreAssignment_3_1");
					put(grammarAccess.getServidor_ImplAccess().getZonaDisponibilidadAssignment_4_1(), "rule__Servidor_Impl__ZonaDisponibilidadAssignment_4_1");
					put(grammarAccess.getServidor_ImplAccess().getZonaNombreAssignment_5_1(), "rule__Servidor_Impl__ZonaNombreAssignment_5_1");
					put(grammarAccess.getServidor_ImplAccess().getTamanoAssignment_6_1(), "rule__Servidor_Impl__TamanoAssignment_6_1");
					put(grammarAccess.getServidor_ImplAccess().getRecursosAssignment_7_2(), "rule__Servidor_Impl__RecursosAssignment_7_2");
					put(grammarAccess.getServidor_ImplAccess().getRecursosAssignment_7_3_1(), "rule__Servidor_Impl__RecursosAssignment_7_3_1");
					put(grammarAccess.getServidor_ImplAccess().getVpcAssignment_8_1(), "rule__Servidor_Impl__VpcAssignment_8_1");
					put(grammarAccess.getSubredAccess().getNombreAssignment_3_1(), "rule__Subred__NombreAssignment_3_1");
					put(grammarAccess.getSubredAccess().getZonaNombreAssignment_4_1(), "rule__Subred__ZonaNombreAssignment_4_1");
					put(grammarAccess.getSubredAccess().getZonaDisponibilidadAssignment_5_1(), "rule__Subred__ZonaDisponibilidadAssignment_5_1");
					put(grammarAccess.getSubredAccess().getCidrBlockAssignment_6_1(), "rule__Subred__CidrBlockAssignment_6_1");
					put(grammarAccess.getSubredAccess().getVpcAssignment_7_1(), "rule__Subred__VpcAssignment_7_1");
					put(grammarAccess.getInternetGatewayAccess().getNombreAssignment_3_1(), "rule__InternetGateway__NombreAssignment_3_1");
					put(grammarAccess.getInternetGatewayAccess().getZonaNombreAssignment_4_1(), "rule__InternetGateway__ZonaNombreAssignment_4_1");
					put(grammarAccess.getInternetGatewayAccess().getZonaDisponibilidadAssignment_5_1(), "rule__InternetGateway__ZonaDisponibilidadAssignment_5_1");
					put(grammarAccess.getInternetGatewayAccess().getVpcAssignment_6_1(), "rule__InternetGateway__VpcAssignment_6_1");
					put(grammarAccess.getGrupoSeguridadAccess().getNombreAssignment_2_1(), "rule__GrupoSeguridad__NombreAssignment_2_1");
					put(grammarAccess.getGrupoSeguridadAccess().getZonaNombreAssignment_3_1(), "rule__GrupoSeguridad__ZonaNombreAssignment_3_1");
					put(grammarAccess.getGrupoSeguridadAccess().getZonaDisponibilidadAssignment_4_1(), "rule__GrupoSeguridad__ZonaDisponibilidadAssignment_4_1");
					put(grammarAccess.getGrupoSeguridadAccess().getDescripcionAssignment_5_1(), "rule__GrupoSeguridad__DescripcionAssignment_5_1");
					put(grammarAccess.getGrupoSeguridadAccess().getVpcAssignment_6_1(), "rule__GrupoSeguridad__VpcAssignment_6_1");
					put(grammarAccess.getGrupoSeguridadAccess().getReglasSalidaAssignment_9(), "rule__GrupoSeguridad__ReglasSalidaAssignment_9");
					put(grammarAccess.getGrupoSeguridadAccess().getReglasSalidaAssignment_10_1(), "rule__GrupoSeguridad__ReglasSalidaAssignment_10_1");
					put(grammarAccess.getGrupoSeguridadAccess().getReglasEntradaAssignment_14(), "rule__GrupoSeguridad__ReglasEntradaAssignment_14");
					put(grammarAccess.getGrupoSeguridadAccess().getReglasEntradaAssignment_15_1(), "rule__GrupoSeguridad__ReglasEntradaAssignment_15_1");
					put(grammarAccess.getReglaAccess().getTipoAssignment_3_1(), "rule__Regla__TipoAssignment_3_1");
					put(grammarAccess.getReglaAccess().getProtocoloAssignment_4_1(), "rule__Regla__ProtocoloAssignment_4_1");
					put(grammarAccess.getReglaAccess().getPuertoAssignment_5_1(), "rule__Regla__PuertoAssignment_5_1");
					put(grammarAccess.getReglaAccess().getOrigenAssignment_6_1(), "rule__Regla__OrigenAssignment_6_1");
					put(grammarAccess.getReglaAccess().getDescripcionAssignment_7_1(), "rule__Regla__DescripcionAssignment_7_1");
				}
			};
		}
		return nameMappings.get(element);
	}

	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			InternalCeffectiveParser typedParser = (InternalCeffectiveParser) parser;
			typedParser.entryRuleCeffective();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public CeffectiveGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(CeffectiveGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
