/*
 * generated by Xtext 2.10.0
 */
package org.xtext.example.ceffective.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.xtext.example.ceffective.ui.internal.CeffectiveActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class CeffectiveExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return CeffectiveActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return CeffectiveActivator.getInstance().getInjector(CeffectiveActivator.ORG_XTEXT_EXAMPLE_CEFFECTIVE_CEFFECTIVE);
	}
	
}
