/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.ceffective.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import org.xtext.example.ceffective.ui.AbstractCeffectiveUiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class CeffectiveUiModule extends AbstractCeffectiveUiModule {
  public CeffectiveUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
