/*
 * generated by Xtext 2.10.0
 */
package org.xtext.example.ceffective.tests

import ceffective.Ceffective
import com.google.inject.Inject
import org.eclipse.xtext.junit4.InjectWith
import org.eclipse.xtext.junit4.XtextRunner
import org.eclipse.xtext.junit4.util.ParseHelper
import org.junit.Assert
import org.junit.Test
import org.junit.runner.RunWith

@RunWith(XtextRunner)
@InjectWith(CeffectiveInjectorProvider)
class CeffectiveParsingTest{

	@Inject
	ParseHelper<Ceffective> parseHelper

	@Test 
	def void loadModel() {
		val result = parseHelper.parse('''
			Hello Xtext!
		''')
		Assert.assertNotNull(result)
	}

}
