/*
 * generated by Xtext 2.10.0
 */
package org.xtext.example.ceffective


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class CeffectiveStandaloneSetup extends CeffectiveStandaloneSetupGenerated {

	def static void doSetup() {
		new CeffectiveStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
