/*
 * generated by Xtext 2.10.0
 */
package org.xtext.example.ceffective.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.example.ceffective.parser.antlr.internal.InternalCeffectiveParser;
import org.xtext.example.ceffective.services.CeffectiveGrammarAccess;

public class CeffectiveParser extends AbstractAntlrParser {

	@Inject
	private CeffectiveGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalCeffectiveParser createParser(XtextTokenStream stream) {
		return new InternalCeffectiveParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Ceffective";
	}

	public CeffectiveGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(CeffectiveGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
